### ISSUE TITLE
Client Secret

### ISSUE THREAD

**Issue by lukeb2e** [aikikode/fileshare#21]
https://github.com/aikikode/fileshare/blob/f6abea6ef67af8442895fa08910d945dab7116a1/upload_services.py#L92

I don't think you should publish this. :)

**Comment by aikikode** [comment]
Hi @lukeb2e, thank for your concern :)
However this is a "secret" that identifies this application, not any specific Imgur user. See https://apidocs.imgur.com/?version=latest#authorization-and-oauth for more details.

This application is meant for public use so I registered and published this info. Otherwise each person that wanted to use `fileshare` app would have to register own Imgur API keys for it, which is not very convenient.
